// Code generated by MockGen. DO NOT EDIT.
// Source: consumersingle.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kgo "github.com/twmb/franz-go/pkg/kgo"
	gomock "go.uber.org/mock/gomock"
)

// Mockclient is a mock of client interface.
type Mockclient struct {
	ctrl     *gomock.Controller
	recorder *MockclientMockRecorder
}

// MockclientMockRecorder is the mock recorder for Mockclient.
type MockclientMockRecorder struct {
	mock *Mockclient
}

// NewMockclient creates a new mock instance.
func NewMockclient(ctrl *gomock.Controller) *Mockclient {
	mock := &Mockclient{ctrl: ctrl}
	mock.recorder = &MockclientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockclient) EXPECT() *MockclientMockRecorder {
	return m.recorder
}

// AllowRebalance mocks base method.
func (m *Mockclient) AllowRebalance() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AllowRebalance")
}

// AllowRebalance indicates an expected call of AllowRebalance.
func (mr *MockclientMockRecorder) AllowRebalance() *clientAllowRebalanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowRebalance", reflect.TypeOf((*Mockclient)(nil).AllowRebalance))
	return &clientAllowRebalanceCall{Call: call}
}

// clientAllowRebalanceCall wrap *gomock.Call
type clientAllowRebalanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *clientAllowRebalanceCall) Return() *clientAllowRebalanceCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *clientAllowRebalanceCall) Do(f func()) *clientAllowRebalanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *clientAllowRebalanceCall) DoAndReturn(f func()) *clientAllowRebalanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarkCommitRecords mocks base method.
func (m *Mockclient) MarkCommitRecords(arg0 ...*kgo.Record) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "MarkCommitRecords", varargs...)
}

// MarkCommitRecords indicates an expected call of MarkCommitRecords.
func (mr *MockclientMockRecorder) MarkCommitRecords(arg0 ...interface{}) *clientMarkCommitRecordsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCommitRecords", reflect.TypeOf((*Mockclient)(nil).MarkCommitRecords), arg0...)
	return &clientMarkCommitRecordsCall{Call: call}
}

// clientMarkCommitRecordsCall wrap *gomock.Call
type clientMarkCommitRecordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *clientMarkCommitRecordsCall) Return() *clientMarkCommitRecordsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *clientMarkCommitRecordsCall) Do(f func(...*kgo.Record)) *clientMarkCommitRecordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *clientMarkCommitRecordsCall) DoAndReturn(f func(...*kgo.Record)) *clientMarkCommitRecordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PauseFetchPartitions mocks base method.
func (m *Mockclient) PauseFetchPartitions(arg0 map[string][]int32) map[string][]int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseFetchPartitions", arg0)
	ret0, _ := ret[0].(map[string][]int32)
	return ret0
}

// PauseFetchPartitions indicates an expected call of PauseFetchPartitions.
func (mr *MockclientMockRecorder) PauseFetchPartitions(arg0 interface{}) *clientPauseFetchPartitionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseFetchPartitions", reflect.TypeOf((*Mockclient)(nil).PauseFetchPartitions), arg0)
	return &clientPauseFetchPartitionsCall{Call: call}
}

// clientPauseFetchPartitionsCall wrap *gomock.Call
type clientPauseFetchPartitionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *clientPauseFetchPartitionsCall) Return(arg0 map[string][]int32) *clientPauseFetchPartitionsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *clientPauseFetchPartitionsCall) Do(f func(map[string][]int32) map[string][]int32) *clientPauseFetchPartitionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *clientPauseFetchPartitionsCall) DoAndReturn(f func(map[string][]int32) map[string][]int32) *clientPauseFetchPartitionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PollRecords mocks base method.
func (m *Mockclient) PollRecords(ctx context.Context, maxPollRecords int) kgo.Fetches {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollRecords", ctx, maxPollRecords)
	ret0, _ := ret[0].(kgo.Fetches)
	return ret0
}

// PollRecords indicates an expected call of PollRecords.
func (mr *MockclientMockRecorder) PollRecords(ctx, maxPollRecords interface{}) *clientPollRecordsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollRecords", reflect.TypeOf((*Mockclient)(nil).PollRecords), ctx, maxPollRecords)
	return &clientPollRecordsCall{Call: call}
}

// clientPollRecordsCall wrap *gomock.Call
type clientPollRecordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *clientPollRecordsCall) Return(arg0 kgo.Fetches) *clientPollRecordsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *clientPollRecordsCall) Do(f func(context.Context, int) kgo.Fetches) *clientPollRecordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *clientPollRecordsCall) DoAndReturn(f func(context.Context, int) kgo.Fetches) *clientPollRecordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResumeFetchPartitions mocks base method.
func (m *Mockclient) ResumeFetchPartitions(arg0 map[string][]int32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResumeFetchPartitions", arg0)
}

// ResumeFetchPartitions indicates an expected call of ResumeFetchPartitions.
func (mr *MockclientMockRecorder) ResumeFetchPartitions(arg0 interface{}) *clientResumeFetchPartitionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeFetchPartitions", reflect.TypeOf((*Mockclient)(nil).ResumeFetchPartitions), arg0)
	return &clientResumeFetchPartitionsCall{Call: call}
}

// clientResumeFetchPartitionsCall wrap *gomock.Call
type clientResumeFetchPartitionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *clientResumeFetchPartitionsCall) Return() *clientResumeFetchPartitionsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *clientResumeFetchPartitionsCall) Do(f func(map[string][]int32)) *clientResumeFetchPartitionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *clientResumeFetchPartitionsCall) DoAndReturn(f func(map[string][]int32)) *clientResumeFetchPartitionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetOffsets mocks base method.
func (m *Mockclient) SetOffsets(arg0 map[string]map[int32]kgo.EpochOffset) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOffsets", arg0)
}

// SetOffsets indicates an expected call of SetOffsets.
func (mr *MockclientMockRecorder) SetOffsets(arg0 interface{}) *clientSetOffsetsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOffsets", reflect.TypeOf((*Mockclient)(nil).SetOffsets), arg0)
	return &clientSetOffsetsCall{Call: call}
}

// clientSetOffsetsCall wrap *gomock.Call
type clientSetOffsetsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *clientSetOffsetsCall) Return() *clientSetOffsetsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *clientSetOffsetsCall) Do(f func(map[string]map[int32]kgo.EpochOffset)) *clientSetOffsetsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *clientSetOffsetsCall) DoAndReturn(f func(map[string]map[int32]kgo.EpochOffset)) *clientSetOffsetsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
