{
 "title": "Kafka",
 "description": "Cluster wide metrics exported by KMinion",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "highThroughputTopics",
    "query": "query_result(topk(15, avg by (topic_name) (avg_over_time(kminion_kafka_topic_high_water_mark_sum[${__range_s}s]))))"
   },
   {
    "name": "topOffsetCommitters",
    "query": "query_result(topk(5, avg by (group_id) (avg_over_time(kminion_kafka_consumer_group_offset_commits_total[${__range_s}s]))))"
   },
   {
    "name": "consumerGroup",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(kminion_kafka_consumer_group_topic_lag,group_id)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kminion_kafka_topic_info{topic_name!=\"__consumer_offsets\"},topic_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Broker Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages in/sec",
     "type": "timeseries",
     "description": "Summed delta between High and Low watermark of all partitions in the given topic. Therefore not accurate for compacted topics that contain compacted records.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name) (rate(kminion_kafka_topic_high_water_mark_sum[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Cluster Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "kminion_kafka_cluster_info" }
     ]
    },
    {
     "title": "Brokers",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      { "expr": "kminion_kafka_broker_info" }
     ]
    },
    {
     "title": "Brokers Online",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "kminion_kafka_cluster_info" }
     ]
    },
    {
     "title": "Log Dir Size by Broker",
     "type": "timeseries",
     "description": "Log dir size across all log dirs, topics and partitions for a given broker.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (broker_id) (kminion_kafka_broker_log_dir_size_total_bytes)",
       "legendFormat": "Broker {{broker_id}}"
      }
     ]
    },
    {
     "title": "Messages in/sec by topic [Top 15]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{topic_name=~\"$highThroughputTopics\"}[$__rate_interval]))",
       "legendFormat": "{{topic_name}}"
      }
     ]
    },
    {
     "title": "Top Offset Committers [Top 5]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (group_id) (rate(kminion_kafka_consumer_group_offset_commits_total{group_id=~\"$topOffsetCommitters\"}[$__rate_interval]))",
       "legendFormat": "{{group_id}}"
      }
     ]
    },
    {
     "title": "Offset commits processed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (kubernetes_pod_name) (rate(kminion_exporter_offset_consumer_records_consumed_total[$__rate_interval]))",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Consumergroup => Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (group_id,topic_name) (kminion_kafka_consumer_group_topic_lag{group_id=\"$consumerGroup\", topic_name=\"$topic\"})",
     "legendFormat": "{{group_id}} => {{topic_name}}"
    }
   ]
  },
  {
   "title": "Topic Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (group_id,topic_name) (kminion_kafka_consumer_group_topic_lag{group_id=\"$consumerGroup\", topic_name=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Messages In vs Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{topic_name=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "Incoming: {{topic_name}}"
    },
    {
     "expr": "avg by (topic_name, group_id) (rate(kminion_kafka_consumer_group_topic_offset_sum{group_id=\"$consumerGroup\", topic_name=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "Consuming: {{topic_name}}"
    }
   ]
  },
  {
   "title": "Messages in per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kminion_kafka_consumer_group_topic_offset_sum{topic_name=~\"$topic\", group_id=~\"$consumerGroup\"}[10s])) by (group_id, topic_name)",
     "legendFormat": "{{group_id}} -> {{topic_name}}"
    }
   ]
  },
  { "title": "Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Message count",
   "type": "timeseries",
   "description": "Summed delta between High and Low watermark of all partitions in the given topic. Therefore not accurate for compacted topics that contain compacted records.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kminion_kafka_topic_high_water_mark_sum{topic_name=~\"$topic\"} or vector(0)\n- \nkminion_kafka_topic_high_water_mark_sum{topic_name=~\"$topic\"} @ start()",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kminion_kafka_topic_info{topic_name=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Cleanup Policy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kminion_kafka_topic_info{topic_name=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Messages in/sec",
   "type": "timeseries",
   "description": "Summed delta between High and Low watermark of all partitions in the given topic. Therefore not accurate for compacted topics that contain compacted records.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{topic_name=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  {
   "title": "Replication Factor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kminion_kafka_topic_info{topic_name=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Subscribed Consumer Groups",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kminion_kafka_consumer_group_topic_lag{topic_name=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Total Log Dir Size",
   "type": "timeseries",
   "description": "Log dir size across all partitions and brokers for the given topic.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (topic_name) (kminion_kafka_topic_log_dir_size_total_bytes{topic_name=\"$topic\"})",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "avg by (partition_id) (kminion_kafka_topic_partition_low_water_mark{topic_name=\"$topic\"})"
    },
    {
     "expr": "avg by (partition_id) (kminion_kafka_topic_partition_high_water_mark{topic_name=\"$topic\"})"
    }
   ]
  }
 ]
}